### ISSUE TITLE
Unhandled Null reference exception

### ISSUE THREAD

**Issue by ivan-ristovic** [milana-kovacevic/k-means#2]
![ss](https://cloud.githubusercontent.com/assets/19779112/21370986/03615cd0-c70f-11e6-9a50-44dc50813bf1.png)

Unsafe indeed... :smile: Happens really often actually... :cry:

**Comment by milana-kovacevic** [comment]
It works every time on my computer... :disappointed:
Try using the 'safe' part of code instead of the 'unsafe' block. Then it will work for sure! But that will probably slow down the program a bit.
